### ISSUE TITLE
simctl.extensions.start fails to start new simulator if simulator with different deviceId is already running

### ISSUE THREAD

**Issue by mattjoss** [phonegap/simctl#9]
1. Call simctl.extensions.start(deviceId1)
2.  Leave simulator running and call simctl.extensions.start(deviceId2)

Simulator does not switch to deviceId2.

When trying to call simctl.install() after second start, the following error is returned...
```
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Invalid device state
```

The bug occurs in 0.0.8, but works correctly in 0.0.6

This can be seen with the attached node.js app.  
[simctl-test.zip](https://github.com/phonegap/simctl/files/166089/simctl-test.zip)

```
// To test, get list of deviceIds from 'xcrun simctl list' and then run the following command twice with diffeent device ids
//node ./index.js {PATH_TO_APP} {DEVICE_ID}
// e.g.
//node ./index.js ~/HelloWorld.app EAA544F1-D533-4168-9F4A-790AFE764DDA
//node ./index.js ~/HelloWorld.app 3F6912C6-1392-40B7-95CC-41A69EC07BCD
```

**Comment by shazron** [comment]
Just checking, is Xcode 7 (Xcode.app) the only Xcode installed in your system?

**Comment by mattjoss** [comment]
Yes, only Xcode 7 installed.

**Comment by shazron** [comment]
Confirmed. Investigating a fix.

**Comment by shazron** [comment]
Reverting back to using Instruments fixes this: https://github.com/phonegap/simctl/commit/704b0f8ca0bb03bf4e87ddeca214bb8f7d5affe6

**Comment by shazron** [comment]
The iOS Simulator really doesn't like to have more than one instance "open"ed, which is probably causing the "Invalid Device State". Instruments intelligently shuts down the previous instance and launches the new one.

**Comment by shazron** [comment]
Fixed in https://github.com/phonegap/simctl/commit/34426c719130a73b83af65f50a11a46267a5ad0b
